version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  TAIGA_SITES_DOMAIN: "localhost"
  TAIGA_SITES_SCHEME: "https"
  # Email settings. Uncomment following lines and configure your SMTP server
  # EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  # DEFAULT_FROM_EMAIL: "no-reply@example.com"
  # EMAIL_USE_TLS: "False"
  # EMAIL_USE_SSL: "False"
  # EMAIL_HOST: "smtp.host.example.com"
  # EMAIL_PORT: 587
  # EMAIL_HOST_USER: "user"
  # EMAIL_HOST_PASSWORD: "password"
  # Registration
  PUBLIC_REGISTER_ENABLED: "False"
  # Telemetry settings
  ENABLE_TELEMETRY: "True"
  # Rabbitmq settings
  # should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Github settings
  # Get these in your profile https://github.com/settings/apps
  # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
  GITHUB_API_CLIENT_ID: "github-api-client-id"
  GITHUB_API_CLIENT_SECRET: "github-api-client-secret"
  # Gitlab settings
  # Get these in your profile https://{YOUR-GITLAB}/profile/applications
  # or in your organization profile https://{YOUR-GITLAB}/admin/applications
  GITLAB_API_CLIENT_ID: "gitlab-api-client-id"
  GITLAB_API_CLIENT_SECRET: "gitlab-api-client-secret"
  GITLAB_URL: "gitlab-url"
  # IMPORTERS
  ENABLE_GITHUB_IMPORTER: "False"
  GITHUB_IMPORTER_CLIENT_ID: "client-id-from-github"
  GITHUB_IMPORTER_CLIENT_SECRET: "client-secret-from-github"
  ENABLE_JIRA_IMPORTER: "False"
  JIRA_IMPORTER_CONSUMER_KEY: "consumer-key-from-jira"
  JIRA_IMPORTER_CERT: "cert-from-jira"
  JIRA_IMPORTER_PUB_CERT: "pub-cert-from-jira"
  ENABLE_TRELLO_IMPORTER: "False"
  TRELLO_IMPORTER_API_KEY: "api-key-from-trello"
  TRELLO_IMPORTER_SECRET_KEY: "secret-key-from-trello"


x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
#  - ./config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: cristianlazarop/taiga_sso:back_sso
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    volumes:
      - ./config.py:/taiga-back/settings/config.py
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/ssl/certs/ca-certificates.crt:/opt/venv/lib/python3.7/site-packages/certifi/cacert.pem
  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-front:
    image: cristianlazarop/taiga_sso:front_sso
    environment:
      TAIGA_URL: "https://localhost"
      TAIGA_WEBSOCKETS_URL: "ws://localhost:8080"
      PUBLIC_REGISTER_ENABLED: "false"
      # Get these in your profile https://github.com/settings/apps
      # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
      GITHUB_CLIENT_ID: "github-client-id"
      # Get these in your profile https://{YOUR-GITLAB}/profile/applications
      # or in your organization profile https://{YOUR-GITLAB}/admin/applications
      GITLAB_CLIENT_ID: "gitlab-client-id"
      GITLAB_URL: "gitlab-url"
      # IMPORTERS
      ENABLE_GITHUB_IMPORTER: "false"
      ENABLE_JIRA_IMPORTER: "false"
      ENABLE_TRELLO_IMPORTER: "false"
    networks:
      - taiga
    volumes:
      - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: "taiga-back-secret-key"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "8080:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:

networks:
  taiga:
